# FROM jarredsumner/bun:edge
FROM node:alpine as builder

WORKDIR /app
COPY package.json package.json
COPY tsconfig.json tsconfig.json
RUN npm install
COPY src src/
RUN npm run build
RUN tar cvzf /tmp/dist.tgz dist

FROM node:alpine
WORKDIR /app
COPY --from=builder /tmp/dist.tgz /app/dist.tgz

COPY package.json package.json
RUN npm install --omit=dev
RUN tar xvzf dist.tgz
EXPOSE 5010
ENTRYPOINT ["node", "dist/"]